module.exports = {
    ROL_APROBADOR_ID: process.env.APPROVER_ROLE_ID,
    CANAL_SOLICITUDES_ID: process.env.REQUEST_CHANNEL_ID,
    CANAL_APROBACIONES_ID: process.env.APPROVAL_CHANNEL_ID,
    MANAGER_CHANNEL_ID: process.env.MANAGER_CHANNEL_ID
};
